### ISSUE TITLE
Package Duplication

### ISSUE THREAD

**Issue by Owen-oj** [DevRaeph/laravel-pdf-protect#1]
Hi Raph, 

What do you intend to achieve with this package that is not already in my package? [Laravel Password Protect](https://github.com/Owen-oj/pdf-password-protect)

**Comment by DevRaeph** [comment]
Hi Owen,
i removed some unnecessary classes, fixed psr4 autoloading issues and modifed the main class:

```
 $pagecount = $mpdf->setSourceFile($inputFile);
        for ($p = 1; $p <= $pagecount; $p++) {
            $tplId = $mpdf->importPage($p);
            $wh = $mpdf->getTemplateSize($tplId);
            if (($p==1)){
                $mpdf->state = 0;
                $mpdf->AddPage($wh['width']>$wh['height']?'L':'P');
                $mpdf->UseTemplate($tplId);
            }
            else {
                $mpdf->state = 1;
                $mpdf->AddPage($wh['width']>$wh['height']?'L':'P');
                $mpdf->UseTemplate($tplId);
            }
        }
```

it was not possible to protect multiple sites (it only took the last one).
Also the orientation was an issue.
I needed it today for a project and that's why i can't wait for adapations.
I hope it's no problem for you and i also credited you in the readme part :)
